### PR TITLE
"adding TPX-8 implementation on 03/12/2024"

### PR DESCRIPTION
**Pull request by cernica24**
Added TPX-8 Implementation. Adding @diamond2602 as a reviewer. If there any changes needed please let me know.

### CODE REVIEW

**Review by diamond2602 — COMMENTED** [review]
can you explains please why we crating another allproposals page and copying everything there from proposalpage. can we just use 1 more proposal page and store everything related to proposals there?

**Comment by cernica24** [comment]
@diamond2602 I took the implementation that I did for TPX-7 from Proposal page and moved it to AllProposalPage , because I realize that Proposal page => it is for creating new Proposal.
I only moved the methods that I added from Proposal page to AllProposalsPage

**Comment by cernica24** [comment]
@diamond2602 if we need to discuss is and change it back let me know

**Comment by cernica24** [comment]
@diamond2602  @mturanus  
I've added all of you to review it. Please let me know if any changes needed. I did spend like 2-3 day to finish it, and I did not get any review or approval for my work!
I do think that Proposal Page it is different from the Page that we see all of the proposals list page. If anyone think different please let me know!!  
Otherwise I can change it back. But if I have no-one respond back, there is no way I can work on it

**Pull request merged**
